### ISSUE TITLE
When running example, I get 400 Bad Request

### ISSUE THREAD

**Issue by tamoyal** [ChronixDB/chronix.go#12]
When running the example [here](https://github.com/ChronixDB/chronix.go/blob/master/example/example.go) verbatim, I get `Error storing time series: bad HTTP response code: 400 Bad Request`.

Note that I replaced the url with my local chronix solr url.

Any idea why this would happen and how to debug?

**Comment by FlorianLautenschlager** [comment]
How does the url look like?

**Comment by tamoyal** [comment]
Thanks so much for the fast response. 

Url is `http://localhost:8983/solr/chronix`

I found the logs which points to a schema problem. I looked at your docs around schema and it's not clear what I need to do (if anything).

From the logs
```
2018-04-03 17:39:33.400 ERROR (qtp1205044462-13) [   x:chronix] o.a.s.h.RequestHandlerBase org.apache.solr.common.SolrException: ERROR: [doc=2da87e94-d68e-4455-bfae-a6c9681b44ea] unknown field 'metric'
```

**Comment by FlorianLautenschlager** [comment]
Yeah found the same. Damn - I will fix this. We changed the name of the required field from "metric" to "name". Thought we have already fixed this. Give me little time.

**Comment by juliusv** [comment]
@FlorianLautenschlager Seems someone attempted to fix this in https://github.com/ChronixDB/chronix.go/pull/11, but that's not merged yet (and apparently not complete either as per your comment).

**Comment by tamoyal** [comment]
I changed `name` to `metric` in the schema to try to work around but got this:
```
2018-04-03 18:28:51.495 ERROR (qtp1205044462-19) [   x:chronix] o.a.s.h.RequestHandlerBase org.apache.solr.common.SolrException: [doc=6dd63c4f-f6b1-4ffb-9892-5cfa19b5fb70] missing required field: type
```

so looks like it's best if I leave it to someone who has been working with Chronix for more than 24 hours ;)

appreciate the fast responses :)

**Comment by juliusv** [comment]
@tamoyal Have you tried also adding the `type` field like in https://github.com/ChronixDB/chronix.go/pull/11/files?

**Comment by tamoyal** [comment]
no, here `chronix-solr-6.4.2/server/solr/chronix/conf/schema.xml`?

**Comment by juliusv** [comment]
@tamoyal No, in chronix/client.go, like in the pull request I linked above.

**Comment by tamoyal** [comment]
@juliusv If I send you guys a PR like the above but with the fixture changed to use `name` instead of `metric` [here](https://github.com/ChronixDB/chronix.go/blob/master/chronix/fixtures/update.json), will that be accepted?

**Comment by FlorianLautenschlager** [comment]
@tamoyal I don't see why. Go ahead ;-)
The type field is also new and has not yet been updated.

**Comment by FlorianLautenschlager** [comment]
@tamoyal i have updated the code - unfortunately `go test`is not working (marked with a todo). But the good news, the example is now working again ;-)

**Comment by tamoyal** [comment]
that worked, thanks!
